### ISSUE TITLE
List of potential improvements

### ISSUE THREAD

**Issue by blablubbabc** [the-w41k3r/ShopkeepersAddon#1]
I very briefly looked through the code. Here are a few of the things I noticed that are specifically related to the integration with Shopkeepers:
* Try to reduce your dependency from the complete `Shopkeepers-2.13.3.jar` to only the API portion `ShopkeepersAPI`. This artifact can be found in this Maven repository: `https://nexus.lichtspiele.org/repository/releases/`. Even if you depend on the complete Shopkeepers jar, try to only use classes and interfaces from the `api` packages. All other classes are likely to change between plugin updates. Even the API classes are still rather unstable, but they should become more stable over time.
* `Commands` class and `InvUtils` class: The `SKShopkeepersPlugin` import does not seem to be used for anything in those classes. And if it is used for something, try to avoid using it, since it is not part of the API portion of Shopkeepers.
* You are using `SKShopkeepersPlugin.getInstance()` for all your Bukkit Scheduler tasks (e.g. in `GuiListeners` and in `ShopGUI`). Don't. Instead, use your own plugin instance for those tasks (i.e. your `Main` class instance).
* `ShopkeeperSorter`: Again, don't use `SKShopkeepersPlugin`. Instead, you can retrieve the ShopkeeperRegistry via `ShopkeepersAPI.getShopkeeperRegistry()`.
* `ShopkeeperSorter#getAllShopOwners` owners, `ShopkeeperSorter#shopkeeperItemStacks` values, `ShopkeeperSorter#sellingItemStacks`: You are currently using ArrayLists for those. Probably because you require access by index inside `ShopGUI`. However, you are currently also doing many containment checks on these collections, for which a Hash-based data structure would be better suited. An idea could be to have both: One Hash-based data structure for efficient containment checks, and a consistently maintained ArrayList based structure for your GUI operations.
* `ShopkeeperSorter`: All your `update` methods (`updateVisualRepresentationOfShopkeepers`, `updateShopkeeperItemstacks`, `updateSellingItemStacks`) are quite wasteful performance-wise. Especially since you invoke them repeatedly (see `GuiListeners`), whenever a shopkeeper changes, is removed, or a player joins. Try to optimize this to not have to recalculate all data freshly on every minor shopkeeper change. Instead, try to only update those portions that might actually be affected by a change. E.g. if a shopkeeper is removed or edited, try to only update the pieces of data that are affected by this particular shopkeeper. And ideally build your data structures in a way that allows you to update this information for a specific shopkeeper efficiently, without having to iterate over all shopkeepers or over all of your cached data to check if one element is affected, etc.
* `ShopkeeperSorter#getAllAdminShopkeepers`: The result of this can probably also be cached instead of being recalculated every time. You only need to add or remove a shopkeeper from your cache whenever a new admin shopkeeper is added to the registry (`ShopkeeperAddedEvent`) or removed (`ShopkeeperRemoveEvent`).
* `ShopkeeperSorter`: You are using `Shopkeeper#getTradingRecipes(Player)` to retrieve (and cache) information about the traded items. There are a few minor problems with this.
  * Minor (not an issue right now, but maybe in the future): In principle, this is allowed to return random or periodically changing results everytime you call it (e.g. some custom type of shopkeeper that periodically changes its trades; or a custom type of shopkeeper that offers each player a randomly picked list of trades). Right now I am not aware of such shopkeeper implementations, but this is a future possibility. Unfortunately, there is no general solution then to retrieve the trade offers of any kind of shopkeeper. Instead, you will probably have to account for each type of shopkeeper individually, and ignore any unknown shopkeeper types (e.g. custom ones like I mentioned above).
  * Minor (not an issue right now, but maybe in the future): You are using one specific player instance to retrieve the trading recipes for. Your cached information is then based on this specific player instance. Although this is not relevant right now, because none of the currently built-in types of shopkeepers actually use the `player` argument, in principle the information you get is not suited for all players on the server. E.g. a custom shopkeeper implementation might offer different players different trades. You would probably need to either ignore these (unknown) types of shopkeepers, or split your cache into 2 portions, one that is player-unspecific, and one that is specific to the player viewing the inventory menu. Though, I don't think that there is a way currently to check if a shopkeeper might return player-specific trade offers..
  * Related to that: Since there are currently no shop types with player-specific trading recipes yet, nor is your cache properly accounting for this future possibility anyway, you can probably just omit the `player` argument for now when you call `#getTradingRecipes(player)`. I.e. simply call `#getTradingRecipes(null)`. This will also simplify a few of your update methods, since they no longer require a player argument.

**Comment by MrF1yn** [comment]
Thanks for taking your time and suggesting improvements. I will be definitely making the changes. Also one thing to note The cache update only happens when a shopkeeper is edited or when the first player joins the server after start and i wont be requiring this method as you mentioned i can pass null instead of having to pass a player.
